version: '3.9'
volumes:
    prometheus_data: {}
    grafana_data: {}
networks:
  prometheus_network:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus:v2.48.0
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    # networks:
    #   - prometheus_network
    network_mode: "host"
    restart: always

  # node-exporter:
  #   image: prom/node-exporter:v1.7.0
  #   container_name: node-exporter-container
  #   restart: unless-stopped
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #   expose:
  #     - 9100
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - prometheus_network

  grafana:
    image: grafana/grafana:9.5.13
    ports:
      - "80:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=EuvouTrocar
      - GF_SECURITY_ADMIN_USER=administrador
    # networks:
    #   - prometheus_network
    network_mode: "host"
    volumes:
      - grafana_data:/var/lib/grafana
      - "./prometheus_ds.yaml:/etc/grafana/provisioning/datasources/prometheus_ds.yaml"
    restart: always
