global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          grupo: "Prometheus"
          
  

