global:
  scrape_interval: 25s
  scrape_timeout: 15s
  evaluation_interval: 25s
  
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          grupo: "Prometheus"
  - job_name: 'nodeEX-docker'
    static_configs:
      - targets: ['node-exporter:9200']
  - job_name: "nodeEX-install"
    static_configs:
      - targets: ["localhost:9100"]
        labels:
          grupo: "vm-azure"
    basic_auth:
      username: "prometheus"
      password: "jM9ijHfrvhoPfJpqos3nTisjQxaHrVrrO081h5aYY6c="
    scheme: https
    tls_config:
      insecure_skip_verify: true
    # Relabeling "instance" to remove the ":9100" part
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'